sodafoundation/installer

- ansible/roles/dashboard-installer/scenarios/use-source-code.yml
To install nodejs normmally, the command `apt-get update` should be executed after adding nodejs source into ubuntu source list.
> Fix bugs when installing nodejs

- ansible/roles/dashboard-installer/scenarios/source-code.yml
Both Nginx and Apache2 use 80 as default server port. If Apache2 is installed previously, then installing nginx will fail. So we can stop apache2 service when installing nginx and restart apach2 after installing and reconfiguring nginx(such as change 80 to 8088).
> Fix 80 port conflict when installing nginx

- ansible/group_vars/osdsdock.yml
- ansible/roles/osdsdock/scenarios/cinder_standalone.yml
1. Fix the workplace doesn't exist issue.
2. Fix the 3306 port conflicts.
> Fix cinder standalone install error

- ansible/group_vars/cinder/cinder.yaml
Currently opensds use `default` as the default availability zone, so changing nova to default.
> Set default availability zone for cinder pool

- ansible/roles/osdsdock/scenarios/cinder_standalone.yml
The dock daemon in opensds reads the cinder configuration and call the `pools api` of cinder to initialize cinder dock, it will take some time to wait for all daemon(such as cinder-api, cinder-scheduler, cinder-volume and so forth) of cinder to start normally.  So we extend the waiting time to ensure that the cinder service is available.
> Set the waiting time of booting cinder service

- ansible/roles/common/tasks/main.yml
The librados and librbd system packages had been installed as part of
the "make all" for the opensds controller rather than being done as
part of the install setup. This fixes that by installing these packages
in a more distro independent way using ansible.
Issue #49
> Install Ceph packages are part of common system packages

- .gitignore
- Makefile
This is part of an effort to standardize how builds are done
across OpenSDS projects. Adding a common "dist" make target
so build artifacts can more easily be collected across the
different deliverables.
Signed-off-by: Sean McGinnis <sean.mcginnis@gmail.com>
> Add dist make target for build packaging

- ansible/group_vars/common.yml
Cherry-pick v0.2.1 change from master to stable/aruba to prepare for the stable/aruba release
> Cherry-pick v0.2.1 ansible change to stable/aruba

- ansible/group_vars/common.yml
This patch is proposed for changing default release version to v0.3.0, so as to comply with OpenSDS Bali milestone-1.
> Change the default release version to v0.3.0

- ansible/group_vars/osdsdock.yml
- ansible/roles/osdsdock/scenarios/ceph.yml
- ansible/script/check_ceph_version.sh
This PR adds capability to skip Ceph installation process if it already exist during OpenSDS cluster installation process using Ansible.
> Enabled OpenSDS Ansible installation with pre-existing Ceph

- ansible/roles/osdsdock/scenarios/cinder_standalone.yml
This package is for Ubuntu/Debian only.
> Add libffi-dev package for cinder blockbox

- ansible/group_vars/osdsdock.yml
- ansible/roles/cleaner/scenarios/backend.yml
- ansible/roles/hotpot-installer/tasks/main.yml
- ansible/roles/osdsdock/tasks/main.yml
- ansible/set_global.sh
In the process of installing Opensds with multiple backends using Ansible, we have made changes in playbooks so that it will install all backends i.e. Ceph, LVM and Cinder_standalone or as per requirement which is reflecting in "opensds.conf" file 
But it is not reflecting in both UI dashboard and "osdsctl pool list" command ( through osdsctl command it is showing the last installed backend) which is showing only one backend from the backends installed.
> Enabled multiple backend in OpenSDS-ansible installer

- ansible/group_vars/hotpot.yml
- ansible/roles/cleaner/tasks/main.yml
- ansible/roles/hotpot-installer/tasks/main.yml
See [Apiserver decouple request](https://github.com/opensds/opensds/pull/614) for detailed information.
Which issue this PR fixes:
1. Update osdslet and osdsapiserver configuration files for opensds global info
2. Add the operation to start the osdsapiserver service
3. Added the operation of clearing osdsapiserver when install_from is not container
4. update hotpot release to 0.6.0
> Add osdsapiserver in opensds-installer

- ansible/group_vars/hotpot.yml
- ansible/roles/cleaner/tasks/main.yml
- ansible/roles/hotpot-installer/tasks/main.yml
See [Add osdsapiserver in opensds-installer](https://github.com/opensds/opensds-installer/pull/130) request for detailed information.
Which issue this PR fixes:
add osdsapiserver daemon start when opensds install from container
> add spiserver  container

- charts/opensds/templates/deployment.yaml
- charts/opensds/templates/service.yaml
- charts/opensds/values.yaml
Considering opensds has supported all containerized deployment, helm charts should also need to update the latest version.
> Update opensds helm charts to latest version

- conf/policy.json
This adds support for the Telemetry APIs to be authorized.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
The authorization level for each API is given in the release note section. This will be tested with the UI integration (which will be done in a day or so).
**Release note**:
"metrics:get": "rule:admin_or_owner",
"metrics:collect": "rule:admin_or_owner",
"metrics:uploadconf": "rule:admin_api",
"metrics:downloadconf": "rule:admin_api",
"metrics:urls": "rule:admin_or_owner"```
```
> Add authorization to telemetry APIs

- ansible/group_vars/nfs/nfs.yaml
- ansible/group_vars/osdsdock.yml
- ansible/roles/cleaner/scenarios/backend.yml
- ansible/roles/osdsdock/scenarios/nfs.yml
- ansible/roles/osdsdock/tasks/main.yml
This PR will add NFS backend into opensds-installer that initialises nfs dock and pool automatically. Since opensds-installer supports multi-backends, therefore I set `lvm,nfs` as default backend list.
> Add NFS driver in installation

- ansible/roles/telemetry-installer/scenarios/clean_telemetry_tools.yml
- ansible/roles/telemetry-installer/scenarios/install_telemetry_tools.yml
- ansible/roles/telemetry-installer/tasks/main.yml
- ansible/script/mod_prometheus_config_for_lvm_exporter.sh
- ansible/script/set_lvm_exporter_service.sh
installer should run lvm_exporter by default as a system service if telemetry install is enabled .
duplicate of https://github.com/opensds/opensds-installer/pull/167 , which  is closed due to lot of conflicts while merging.
> Telemetry: fix for #163 - Install lvm exporter

- ansible/roles/cleaner/tasks/main.yml
- ansible/roles/orchestration-installer/scenarios/stackstorm.yml
This PR will separate the knwon failure. And report failure when virtualenv for OpenSDS pack of StackStorm installed and ignore this failure.
> Separate known failure task of orchestration install

- ansible/script/set_nginx_config.sh
Fixes [opensds/opensds-dashboard # 106](https://github.com/opensds/opensds-dashboard/issues/106)
The nginx configuration for the orchestration api server needs to be modified.  
Currently all the opensds apis are being served on /v1beta on the 50040 port. Orchestration apis are being served on /v1beta as well but on the 5000 port.   
The routes have to be matched and the API calls have to be rerouted to the appropriate endpoints by the nginx conf. This will be fixed in subsequent PRs
> Fixes opensds/opensds-dashboard # 106. Added the nginx conf change for orchestration api server.

- ansible/group_vars/telemetry.yml
- ansible/roles/telemetry-installer/scenarios/install_telemetry_tools.yml
- ansible/roles/telemetry-uninstaller/scenarios/clean_telemetry_tools.yml
Grafana repository from packge-cloud repository has been moved, hence grafana installation is failing from ansible installer .
taking stable release from original repo and made grafana repository as configurable item.
which issue
#234
> Telemetry: Fix for issue #234

- salt/srv/pillar/opensds.sls
- salt/srv/pillar/salt.sls
- salt/srv/salt/install/telemetry.sls
- salt/srv/salt/remove/telemetry.sls
Salt install telemetry tools (tracking ansible installer).  Uses [upstream saltstack-formulas](https://github.com/saltstack-formulas/opensds-formula#opensds-telemetry)
- Add fix for breaking change in upstream salt nginx-formula.
>  chore(salt): install telemetry tools with salt

- ansible/roles/common/tasks/main.yml
- ansible/site.yml
This PR will avoid repeated 'common' role execution which is already executed in a host. 
The 'allow_duplicates: false' is not working with import_role/include_role in latest ansible. (https://github.com/ansible/ansible/issues/32888).
This PR uses set_fact module that survive between plays but will not be saved across executions.
> Remove repeated common role execution

- salt/pillar_roots/salt.sls
This ensures correct ubuntu repo is setup when `installer.sh -i salt` executes.
> fix(salt): enforce python3 for salt state

- ansible/script/keystone.sh
- ansible/script/ministone.py
This PR fixes #258.
Add endpoint update operations to ansible/script/keystone.sh using a new helper script ministone.py on keystone docker installation case. ministone.py does not require any additional dependencies.
> fix(ansible): update endpoints after keystone container installation (#258)

- ansible/roles/osdsdb/scenarios/container.yml
This PR fixes issue #262.
Add docker-py pip installation task to ansible/roles/osdsdb/scenarios/container.yml.
> fix(ansible): add pip install docker-py to osdsdb container installation scenario

- salt/file_roots/install/salt.sls
- salt/salter.sh
This PR checks assumption _a modern `bash version 4 or later` is installed_ and addresses `line 23: declare: -A: invalid option` errors with old bash.
For example, a newly installed MacOS has old bash version (see: https://itnext.io/upgrading-bash-on-macos-7138bd1066ba).
PR verified on Ubuntu/MacOS.
> fix(salt): check bash version is modern, esp macos

- ansible/group_vars/ceph/all.yml
- ansible/group_vars/ceph/ceph.yaml
- ansible/group_vars/osdsdock.yml
- ansible/install_ansible.sh
- ansible/roles/osdsdock/scenarios/ceph.yml
- ansible/roles/osdsdock/scenarios/ceph_install.yml
- ansible/roles/osdsdock/scenarios/ceph_pool_check.yml
- ansible/roles/osdsdock/scenarios/ceph_preflight_check.yml
- ansible/roles/osdsdock/scenarios/ceph_stabilize.yml
- ansible/roles/osdsdock/scenarios/ceph_uninstall.yml
- ansible/roles/osdsdock/tasks/main.yml
- ansible/site.yml
This PR implements step1, step2 and a part of step3 of #270.
* Improvements:
* Can be a workaround for #252, #255, opensds/opensds#989 and opensds/opensds#991.
* Supports:
1. all-in-one opensds+ceph setup onto a fresh xenial box without ceph packages
2. all-in-one opensds+ceph setup onto a fresh xenial box with distro bundled ceph packages/files but not configured as a ceph client correctly
3. all-in-one opensds setup onto a xenial box pre-configured as a client against an existing (typically external) ceph cluster
* Changes:
* Now default branch of ceph-ansible is 'stable-3.1' that supports 'mimic'.
* Default ceph pool to be created is 'osdsrbd', not 'rbd'.
> Ansible Ceph integration improvements (#270)

- salt/salter.sh
This is workaround for upstream issue https://github.com/saltstack/salt/issues/54765 
To be fixed in 2019.2.2 (https://github.com/saltstack/salt/pull/54780)
> chore(salt): pin salt to stable 2019.2.0

- ansible/roles/auth-installer/tasks/main.yml
This PR add check for port 80 usage. If it is free installation proceeds otherwise installation fails with message. The keystone installation requires port 80 to be free.
This PR address issue #277
> Add port usage check to installer

- ansible/roles/common/tasks/main.yml
OpenSDS installation fails if python package 'requests' is missing in the Ubuntu host system. This PR add installation requests package to installer.
This PR address issue #282
> Python package requests needed when installing from VirtualBox

- conf/policy.json
Considering the update of hotpot policy.json, this pr will sync policy.json to installer so that hotpot is able to serve host api: opensds/opensds#1039
> Add host policy configuration

- ansible/group_vars/ceph/ceph.yaml
- ansible/group_vars/cinder/cinder.yaml
- ansible/group_vars/lvm/lvm.yaml
- ansible/group_vars/nfs/nfs.yaml
- charts/OpenSDS Installation using Helm.md
Config files of backend drivers (/etc/opensds/driver/*.yaml) needs to be updated with replaced 'isSpaceEfficient' parameter.
> Replace backend parameter isSpaceEfficient from config files

- ansible/group_vars/common.yml
- ansible/roles/cleaner/tasks/main.yml
- ansible/roles/common/scenarios/release.yml
- ansible/roles/gelato-installer/scenarios/release.yml
- ansible/roles/sushi-installer/scenarios/release.yml
- ansible/site.yml
This PR address issue #278 and add following features
Add options (source_purge and database_purge) to control delete source files and db before re-install. Installed source packages from /opt folder may be reused in new VM and avoid re-downloading.
> Optimizations to re-use downloaded release directories

- ansible/group_vars/netapp/ontap/ontap.yaml
- ansible/group_vars/osdsdock.yml
- ansible/roles/osdsdock/scenarios/ontap.yml
- ansible/roles/osdsdock/tasks/main.yml
**What this PR does / why we need it:**
This PR is to support for Enabling NetApp ONTAP as a backend for the OpenSDS Hotpot
**Which issue this PR fixes (optional, in fixes #(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged):** fixes #308 
**Special notes for your reviewer:**
This is the installer implementation corresponding to the implementation PR opensds/opensds#1135
> Add NetApp ONTAP Backend Support as the South Bound Driver for OpenSDS Hotpot

- ansible/group_vars/osdsdock.yml
- ansible/roles/osdsdock/scenarios/ontap.yml
- ansible/roles/osdsdock/tasks/main.yml
**What this PR does / why we need it:**
This PR is to update Configuration for NetApp ONTAP SAN as a backend for the OpenSDS Hotpot
**Which issue this PR fixes (optional, in fixes #(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged):** fixes #308 
**Special notes for your reviewer:**
This is the installer implementation corresponding to the implementation PR opensds/opensds#1135
> Update NetApp ONTAP SAN Configurations for NetApp ONTAP Driver

- ansible/group_vars/common.yml
- charts/OpenSDS Installation using Helm.md
- charts/csiplugin-block/values.yaml
- charts/csiplugin-file/values.yaml
- charts/opensds/values.yaml
- charts/servicebroker/values.yaml
This pr will update the rc3 relase tag(0.8.0) in installer config file which will enable user install opensds with the latest release.  It depends on hotpot, gelato, nbp rc3 release. CI will succeed after these projects publish 0.8.0 tag.
> Update release tag: v0.8.0

- ansible/roles/orchestration-installer/scenarios/stackstorm.yml
This is a workaround in installer when Stackstorm installation do not start mistral service as expected
> Add workaround for cases when mistral services are not running

- ansible/roles/osdsdb/scenarios/etcd.yml
Add ip and port for etcd running status check to avoid that etcd would not run when another etcd is running on the host.
Type: Bug Fix
Issue: #313
> Add ip and port for etcd running status check

- Makefile
Add contrib folder to make dist target which is contains grafana configurations
> Include contrib folder to distribution target

- ansible/roles/cleaner/tasks/main.yml
Some docker containers are not removed after clean, this PR ensure they are removed
> Stop & Remove docker containers of Dashboard and Hotpot services

- Makefile
- README.md
- ansible/group_vars/common.yml
- ansible/group_vars/hotpot.yml
- ansible/roles/cleaner/scenarios/release.yml
- ansible/roles/cleaner/scenarios/repository.yml
- ansible/roles/common/scenarios/release.yml
- ansible/roles/common/scenarios/repository.yml
- ansible/roles/common/tasks/main.yml
- ansible/roles/telemetry-installer/scenarios/install_telemetry_tools.yml
- ansible/site.yml
- charts/OpenSDS Installation using Helm.md
- charts/csiplugin-block/values.yaml
- charts/csiplugin-file/values.yaml
- charts/opensds/values.yaml
- charts/servicebroker/values.yaml
Update the installer to support opensds project decoupling to api, controller and dock
(Earlier github.com/opensds/opensds has been migrated to github.com/sodafoundation/opensds and this project/repo has been decoupled to github.com/sodafoundation/api , github.com/sodafoundation/controller and github.com/sodafoundation/dock)
> Update installer to support opensds project decoupling

- ansible/roles/sim-installer/scenarios/rabbitmq.yml
Allow unauth packages for rabbitmq install
/kind bug fix
This PR allows rabbitmq package to install unauthorized dependant packages
Fixes #358 
> /kind TESTED
> Allow unauth packages for rabbitmq install

- ansible/group_vars/netapp/ontap/ontap_nas.yaml
- ansible/group_vars/osdsdock.yml
- ansible/roles/osdsdock/scenarios/ontap.yml
- ansible/roles/osdsdock/scenarios/ontap_nas.yml
- ansible/roles/osdsdock/tasks/main.yml
> /kind design
This adds support for adding NetApp NAS as storage backend while installing through Ansible. 
Fixes #384 
/kind TESTED
```
root@aks:~/gopath/src/github.com/sodafoundation/installer/ansible# osdsctl dock list …
```
> Adding support for NetApp NAS as backend installation

- ansible/group_vars/osdsdock.yml
>
Here in installer/ansible/group_vars/osdsdock.yml file, its given
enabled_backends: netapp_ontap_nas
We need to enable readily  available native driver as the default driver setup so,changed to
enabled_backends: lvm,nfs
Fixes #
> /kind TESTED
Before change file is:
After change file is:
> enabled_backends change

- ansible/roles/cleaner/scenarios/srm-toolchain.yml
- ansible/roles/gelato-installer/scenarios/repository.yml
/kind bug fix
This PR fixes the issue of SRM Toolchain uninstall failing to delete the /opt/srm-toolchain folder even when SRM toolchain has not been installed.
The SRM toolchain uninstaller was executing change to and  delete folder even when the folder was not created. This was due to a missing check on the folder existence.
This has been added.
Fixes #417 
/kind TESTED
> Fixed issue with uninstall SRM toolchain when not exists

- ansible/roles/dashboard-installer/tasks/main.yml
- ansible/site.yml
This PR fixes the dashboard installation issue when auth strategy is set to noauth.
When the auth strategy is set to noauth the dashboard will not be installed. If user wishes to install dashboard they can then install keystone and dashboard using the tags.
Fixes #419 
/kind TESTED
> Fixed dashboard installation when auth strategy is noauth

- ansible/srm-toolchain/grafana/dashboards/default-dashboard.json
- ansible/srm-toolchain/grafana/dashboards/storage-details-dashboard.json
This PR fixes the default grafana dashboard display to show continuous graphs even though the collection of metrics happens once every 15 minutes. instead of showing gaps in the grafana charts we now show a connected graph.
Fixes #
/kind TESTED
> Updated the default grafana dashboards to show connected graphs instead of with breaks

- ansible/srm-toolchain/grafana/dashboards/default-dashboard.json
- ansible/srm-toolchain/grafana/dashboards/storage-details-dashboard.json
This PR updates the viewing window of Grafana dashboards from last 30 minutes to last 24hours.
The metrics are being generated every 15minutes now and there may be times when the last 30 minutes may not have any data points. For this the viewing window is now increased to 24 hours.
Fixes #
/kind TESTED
> Updated the Grafana viewing window from last 30m to 24h

- ansible/roles/delfin-installer/scenarios/rabbitmq.yml
/kind bug fix
This PR fixes the broken bintray links in rabbitmq installation as part of the Delfin installer.
Fixes #456 
/kind TESTED
This is tested with the GitHub Actions migration test.
The passed CI can be seen [here](https://github.com/anvithks/installer/runs/2501558327?check_suite_focus=true)
From the CI run
```
TASK [delfin-installer : Import RabbitMQ public key] ***************************
task path: /home/runner/work/installer/installer/ansible/roles/delfin-installer/scenarios/rabbitmq.yml:24
changed: [localhost] => {"changed": true, "failed": false}
TASK [delfin-installer : Add RabbitMQ official repo] ***************************
task …
```
> Fixed broken bintray links in rabbitmq installation for Delfin

- ansible/roles/delfin-installer/scenarios/rabbitmq.yml
/kind bug fix
This PR fixes the issue of RabbitMQ installation failing on Ubuntu18.04.
After the dead bintray links were replaced in #457 the installation was successding on Ubuntu16.04 but failed on Ubuntu18.04.
Turns out the keys needed for `rabbitmq-erlang` and `rabbitmq-server` needed to be downloaded and set up with apt-key.
This PR adds those keys and also updates the links of the apt-repositories for the above.
Fixes #456 
/kind TESTED
[This](https://github.com/anvithks/installer/actions/runs/819964441) is the workflow run for the PR where this was tested using the Github actions.
> Updated the RabbitMQ steps as per the official installer to fix installation issue on Ubuntu 18.04

- ansible/group_vars/common.yml
- ansible/roles/dashboard-installer/scenarios/container.yml
This PR adds the `enable_storage_service_plans` flag to allow the user to inform the client (SODA Dashboard ) whether the SODA multicloud  should be displayed with Storage Service plans or backends from the dashboard.
Fixes #463 
/kind TESTED
> Added flag to enable and disable storage service plans

- .github/workflows/ci_pull_request.yml
- .github/workflows/ci_push.yml
- ansible/group_vars/common.yml
- ansible/roles/cleaner/tasks/main.yml
- ansible/roles/common/tasks/main.yml
- ansible/roles/dashboard-installer/scenarios/container.yml
- ansible/roles/delfin-installer/scenarios/rabbitmq.yml
- ansible/roles/gelato-ha-uninstaller/scenarios/clean_gelato_ha.yml
- ansible/roles/ha-ip-update/tasks/main.yml
- ansible/roles/osdsdb/scenarios/etcd.yml
- ansible/roles/osdsdock/scenarios/cinder_standalone.yml
- ansible/script/keystone.sh
- ansible/script/ministone.py
- charts/opensds/values.yaml
This PR enables installation of SODA on Ubuntu 20.04.
- Python2 is deprecated in Ubuntu20.04 and not available. All `python-pip` installations are upgraded to `python3-pip`
- All scripts running python2 scripts are now executed with python3
- Ansible version is updated to 2.9.6 (The default supported version for the ceph-ansible version supported)
- Changed the ansible variable syntax to updated syntax for Ansible 2.9. Changed usage of single and double quotes. 
- `install_as_systemd` is set to `false`. Bring api, controller and dock as standalone processes.
- Added an other variable called `install_etcd_as_systemd` and set it to `false`. etcd is also brought up as a standalone process.
- Updated the CI …
> Added changes to support and enable installation of SODA on Ubuntu20.04

- ansible/install_dependencies.sh
This PR is to ensure installed setuptools version, which is compatible with other modules of the project.
If setuptools version is higher than 65, downgrade it to 65
Latest version of Python3 module `setuptools` is not compatible pip module and causes install failure when pip is used
Fixes #510 
> /kind TESTED
> Fix setuptools version for install failure

- README.md
>
> /kind design
kind documentation
This PR fixes a command in the README file. Read issue #512 for more information.
Fixes two issues mentioned in #512:
- Moved "cd installer/ansible" above the "git checkout"
- Corrected version tag of git checkout command
> /kind TESTED
N/A
**Special notes for …
> Fixed git checkout command in README (Issue #512)
