sodafoundation/installer

- charts/opensds/Chart.yaml
- charts/opensds/templates/_helpers.tpl
- charts/opensds/templates/deployment.yaml
- charts/opensds/templates/service.yaml
- charts/opensds/values.yaml
This patch is submitted for moving the helm deployment script
from opensds to this project.
> Add helm deployment script

- ansible/clean.yml
- ansible/roles/common/scenarios/repository.yml
- ansible/roles/common/tasks/main.yml
- ansible/roles/dashboard-cleaner/scenarios/use-source-code.yml
- ansible/roles/dashboard-installer/scenarios/use-source-code.yml
- ansible/roles/keystone-cleaner/tasks/main.yml
- ansible/roles/keystone-installer/tasks/main.yml
- ansible/script/check_ansible_version.sh
Solve Issue [#7](https://github.com/opensds/opensds-installer/issues/7)
Solve Issue [#7](https://github.com/opensds/opensds-installer/issues/9)
Solve Issue [#7](https://github.com/opensds/opensds-installer/issues/10)
> Install keystone and dashboard

- ansible/group_vars/common.yml
- ansible/group_vars/dashboard.yml
- ansible/group_vars/keystone.yml
- ansible/group_vars/osdsdb.yml
- ansible/roles/common/tasks/main.yml
- ansible/roles/dashboard-cleaner/scenarios/use-container.yml
- ansible/roles/dashboard-installer/scenarios/use-container.yml
- ansible/roles/dashboard-installer/scenarios/use-source-code.yml
- ansible/roles/dashboard-installer/tasks/main.yml
- ansible/roles/keystone-cleaner/tasks/main.yml
- ansible/roles/keystone-installer/tasks/main.yml
This patch is mainly pushed for fixing some typo errors and removing some unnecessary variables.
@BaiHuoYu Please take a check.
> Fix some typo errors

- ansible/INSTALL.md
- ansible/group_vars/lvm/lvm.yaml
- ansible/group_vars/osdsdock.yml
- ansible/roles/cleaner/tasks/main.yml
- ansible/roles/dashboard-installer/scenarios/use-source-code.yml
- ansible/roles/osdsdock/scenarios/cinder_standalone.yml
- ansible/roles/osdsdock/scenarios/lvm.yml
- conf/driver/lvm.yaml
Current the lvm volume group is configured by manually , these operations should be automatic
> Simplify the volume group configuration of lvm

- ansible/roles/common/scenarios/release.yml
- ansible/roles/common/scenarios/repository.yml
- ansible/roles/common/tasks/main.yml
- ansible/roles/nbp-installer/scenarios/release.yml
- ansible/roles/nbp-installer/scenarios/repository.yml
- ansible/roles/nbp-installer/tasks/main.yml
- ansible/site.yml
This patch has some changes below:
* Set `nbp-installer` role as optional so that user don't have to install nbp project all the time.
* Copy some install scripts in nbp from repository.
> Update ansible scripts and fix some bugs

- ansible/group_vars/auth.yml
- ansible/roles/nbp-installer/scenarios/csi.yml
> nbp install with keystone

- ansible/roles/cleaner/scenarios/repository.yml
1. add the judgment condition when cleaning nbp data .
> Fix some bugs

- ansible/roles/osdsdb/scenarios/etcd.yml
Add etcd connection info in checking etcd cluster health command
> Specify etcd endpoint in checking etcd cluster health command

- ansible/group_vars/common.yml
- ansible/group_vars/osdsdb.yml
- ansible/group_vars/osdsdock.yml
- ansible/group_vars/osdslet.yml
- ansible/roles/cleaner/tasks/main.yml
- ansible/roles/common/scenarios/release.yml
- ansible/roles/dashboard-installer/scenarios/container.yml
- ansible/roles/nbp-installer/scenarios/flexvolume.yml
- ansible/roles/nbp-installer/scenarios/release.yml
- ansible/roles/osdsdb/scenarios/container.yml
- ansible/roles/osdsdb/tasks/main.yml
- ansible/roles/osdsdock/tasks/main.yml
- ansible/roles/osdslet/tasks/main.yml
This patch makes some updates below:
* Update the default installation from source code to release files
* Fix some bugs when installing sushi flexvolume plugin from release
* Add global variable `ansible_os_family`
> Update default installation from source code to release

- ansible/group_vars/common.yml
This patch is proposed for changing default release version from v0.2.0 to v0.2.1
> Change default release version to v0.2.1

- conf/policy.json
Add An Api for Return Availability Zones of Pools
> Adds an API to return Availability Zones for pools

- ansible/group_vars/common.yml
- conf/policy.json
This PR merges changes from development to master to prepare for Bali milestone-1 release.
> Merge from Development to Master to prepare for Bali milestone-1

- ansible/README.md
- ansible/roles/common/tasks/main.yml
- ansible/roles/nbp-installer/scenarios/csi.yml
- ansible/roles/nbp-installer/scenarios/flexvolume.yml
- ansible/roles/nbp-installer/scenarios/repository.yml
- ansible/roles/nbp-installer/tasks/main.yml
- ansible/roles/osdsdb/scenarios/etcd_aarch64.yml
- ansible/roles/osdsdb/tasks/main.yml
- ansible/roles/osdsdock/scenarios/ceph.yml
- ansible/site.yml
Here are some feedback from OPNFV team:
* Add `pip install notario` when ceph backend enabled
* Ignore the failure of checking ceph osd and mon service
* Add etcd_aarch64 installation
* Move nbp-installer in the place after osdsdock role
> Address feedback from OPNFV team

- ansible/install_ansible.sh
Solved the problem of installing different ansible versions will fail。
modify the file install_ansible.sh
1. remove old ansible before install a new one
apt-get remove -y ansible
apt-get purge -y ansible
2. remove the PPA associated with the old version
sudo add-apt-repository -r ppa:ansible/ansible-2.4
> Optimize Ansible Install Script

- ansible/script/keystone.sh
> Remove hardcoded username

- ansible/global.sh
- ansible/script/vars.sh
> Add Global vars for ansible

- ansible/group_vars/common.yml
This PR updates version to point to v0.3.1 of nbp and hotpot for Bali milestone-2 release.
> Update version to point to v0.3.1 of nbp and hotpot

- charts/csiplugin/templates/csi-attacher-opensdsplugin.yaml
- charts/csiplugin/templates/csi-configmap-opensdsplugin.yaml
- charts/csiplugin/templates/csi-nodeplugin-opensdsplugin.yaml
- charts/csiplugin/templates/csi-provisioner-rbac.yaml
- charts/csiplugin/templates/csi-snapshotter-opensdsplugin.yaml
- charts/csiplugin/templates/csi-snapshotter-rbac.yaml
- charts/csiplugin/values.yaml
- charts/opensds/templates/deployment.yaml
According to the feedback from Yahoo developers, we found that the csi plugin helm charts template is out of date, so this patch is proposed for updating the template and fixing some bugs.
@xing-yang @stmcginnis Please take a look, thanks!
> Fix some helm chart bugs and update csi version to v0.4.0

- ansible/group_vars/dashboard.yml
- ansible/roles/dashboard-installer/scenarios/source-code.yml
- ansible/script/set_nginx_config.sh
This patch is designed to update some installation steps of opensds-dashboard.
> Update some dashboard install scripts

- ansible/group_vars/common.yml
This PR updates version of nbp and hotpot in the ansible-playbook
for the Bali RC release.
> Update nbp and hotpot version in ansible-playbook

- ansible/roles/dashboard-installer/scenarios/container.yml
make host ip configruable for dashborad
> make host ip configruable for dashborad

- ansible/script/keystone.sh
overlay the opensds configuration file text.
> overlay the configuration file text

- ansible/group_vars/ceph/all.yml
- ansible/group_vars/dashboard.yml
- ansible/group_vars/gelato.yml
- ansible/group_vars/hotpot.yml
- ansible/group_vars/sushi.yml
- ansible/script/check_ansible_version.sh
- ansible/script/global_vars.sh
- ansible/script/keystone.sh
- ansible/script/set_nginx_config.sh
- ansible/script/util.sh
- ansible/set_global.sh
- charts/README.md
- charts/servicebroker/Chart.yaml
- charts/servicebroker/templates/_helpers.tpl
- charts/servicebroker/templates/broker-deployment.yaml
- charts/servicebroker/templates/broker-service.yaml
- charts/servicebroker/templates/broker.yaml
- charts/servicebroker/values.yaml
This PR merges changes from master to stable/bali to prepare for the Bali release.
> Merge changes from master to stable/bali

- ansible/roles/osdsdock/scenarios/cinder_standalone.yml
> Fix a typo error in cinder ansible script

- ansible/group_vars/dashboard.yml
- ansible/group_vars/gelato.yml
- ansible/group_vars/hotpot.yml
- ansible/group_vars/sushi.yml
This PR updates OpenSDS versions to prepare for the Capri
milestone-1 release.
> WIP Update OpenSDS versions

- ansible/roles/osdsdock/scenarios/cinder_standalone.yml
- ansible/roles/osdsdock/scenarios/lvm.yml
> update text to say loading kernel module

- ansible/group_vars/cinder/cinder.yaml
- ansible/roles/hotpot-installer/tasks/main.yml
- ansible/script/keystone.sh
Please see [design spec](https://github.com/opensds/design-specs/pull/19) for more details.
> Modify keystone and cinder configuration file for encryption and decryption.

- ansible/group_vars/ceph/conf.yml
- ansible/roles/osdsdock/scenarios/ceph.yml
- ansible/script/check_ceph_exist.sh
- ansible/site.yml
premise condition：
CEPH has been deployed in the backend.
1. determine whether CEPH is deployed by the CEPH command "ceph health".
2. If the CEPH backend already exists, add the backend information in group_vars/osdsdock.yml first
> add ceph backend config

- ansible/docs/OpenSDS Multi-nodes installation using Ansible.md
- ansible/group_vars/auth.yml
- ansible/roles/auth-installer/tasks/main.yml
- ansible/roles/cleaner/scenarios/auth-keystone.yml
- ansible/roles/gelato-installer/tasks/main.yml
- ansible/roles/hotpot-installer/tasks/main.yml
- ansible/script/keystone.sh
> install keystone with docker

- ansible/clean.yml
- ansible/roles/cleaner/scenarios/auth-keystone.yml
- ansible/roles/cleaner/scenarios/repository.yml
- ansible/roles/common/scenarios/release.yml
- ansible/roles/common/scenarios/repository.yml
- ansible/roles/common/tasks/main.yml
- ansible/roles/grafana-installer/tasks/main.yml
- ansible/roles/grafana-uninstaller/tasks/main.yml
- ansible/roles/hotpot-installer/tasks/main.yml
- ansible/roles/osdsdb/tasks/main.yml
- ansible/roles/osdsdock/scenarios/lvm.yml
- ansible/roles/osdsdock/tasks/main.yml
- ansible/roles/sushi-installer/scenarios/release.yml
- ansible/roles/sushi-installer/scenarios/repository.yml
This PR contains several changes below:
* Add `-f` flag so that grafana can be installed.
* Remove some `ignore_errors` fields.
* Remove some duplicated validate flags.
> Fix some bugs in grafana installer

- ansible/group_vars/hotpot.yml
- ansible/group_vars/sushi.yml
- charts/csiplugin/Chart.yaml
- charts/opensds/Chart.yaml
- charts/servicebroker/Chart.yaml
> Update latest version

- ansible/clean.yml
- ansible/group_vars/orchestration.yml
- ansible/roles/cleaner/scenarios/orchestration.yml
- ansible/roles/cleaner/tasks/main.yml
- ansible/roles/orchestration-installer/scenarios/source-code.yml
- ansible/roles/orchestration-installer/scenarios/stackstorm.yml
- ansible/roles/orchestration-installer/scenarios/start-orchestration.yml
- ansible/roles/orchestration-installer/tasks/main.yml
- ansible/script/virtualenv_exec.j2
- ansible/site.yml
- ci_check.sh
This PR add support for installation of OpenSDS Orchestration Manager
> Add OpenSDS Orchestrator to the installer

- ansible/group_vars/telemetry.yml
- ansible/roles/hotpot-installer/tasks/main.yml
- ansible/roles/telemetry-installer/scenarios/install_telemetry_tools.yml
This PR will update telemetry installation details to OpenSDS config file
> Add Telemetry configs to OpenSDS Config file

- ansible/roles/telemetry-installer/scenarios/clean_telemetry_tools.yml
- ansible/roles/telemetry-installer/scenarios/install_telemetry_tools.yml
- ansible/roles/telemetry-uninstaller/scenarios/clean_telemetry_tools.yml
> install sysstat

- ansible/roles/telemetry-installer/scenarios/clean_telemetry_tools.yml
- ansible/roles/telemetry-installer/scenarios/install_telemetry_tools.yml
- ansible/script/mod_prometheus_config_for_pushgateway.sh
- ansible/script/set_alertmanager_service.sh
This PR will fix issue #161. Alertmanager is changed to run as service. After pushgateway installation, Prometheus configuration is changed and restarted.
> Fix telemetry issue161

- ansible/group_vars/dashboard.yml
- ansible/group_vars/hotpot.yml
- ansible/group_vars/sushi.yml
- charts/csiplugin/Chart.yaml
- charts/csiplugin/values.yaml
- charts/opensds/Chart.yaml
- charts/opensds/values.yaml
- charts/servicebroker/Chart.yaml
- charts/servicebroker/values.yaml
> modify the version tags

- ansible/clean.yml
- ansible/group_vars/auth.yml
- ansible/group_vars/common.yml
- ansible/group_vars/dashboard.yml
- ansible/group_vars/gelato.yml
- ansible/group_vars/hotpot.yml
- ansible/group_vars/orchestration.yml
- ansible/group_vars/osdsdb.yml
- ansible/group_vars/osdsdock.yml
- ansible/group_vars/sushi.yml
- ansible/group_vars/telemetry.yml
- ansible/roles/cleaner/tasks/main.yml
- ansible/roles/telemetry-installer/tasks/main.yml
- ansible/site.yml
- ci_check.sh
> Make all service tags configured in common.yml

- ansible/group_vars/telemetry.yml
- ansible/roles/telemetry-installer/scenarios/install_telemetry_tools.yml
Telemetry: Fixing issue https://github.com/opensds/opensds-installer/issues/189 and    https://github.com/opensds/opensds-installer/issues/185
> Telemetry: Fixing issue https://github.com/opensds/opensds-installer/issues/189 and    https://github.com/opensds/opensds-installer/issues/185

- ansible/group_vars/common.yml
- charts/csiplugin/Chart.yaml
- charts/csiplugin/values.yaml
- charts/opensds/Chart.yaml
- charts/opensds/values.yaml
- charts/servicebroker/Chart.yaml
- charts/servicebroker/values.yaml
modify the tag version to v0.5.4
> modify the tag version to v0.5.4

- ansible/group_vars/orchestration.yml
- ansible/roles/orchestration-installer/scenarios/start-orchestration.yml
This PR add orchestration configuration file modifications required for Orchestration Service.
This PR depends on (https://github.com/opensds/orchestration/pull/70)
> Add installation config to orchestration configuration file

- ansible/roles/cleaner/scenarios/orchestration.yml
- ansible/roles/orchestration-installer/scenarios/stackstorm.yml
- ansible/roles/orchestration-installer/scenarios/start-orchestration.yml
- ansible/script/orchestration_addservices.py
This PR will register Orchestration Services through Installer.
This PR depend on https://github.com/opensds/opensds-installer/pull/202
> Register Orchestration services

- ansible/roles/dashboard-installer/scenarios/container.yml
- ansible/script/orchestration_addservices.py
- ansible/script/set_nginx_config.sh
Reverted older changes from #209  and #205
> Reverted fix for opensds/opensds-dashboard #106. 

- ansible/group_vars/orchestration.yml
- ansible/roles/orchestration-installer/scenarios/start-orchestration.yml
This PR appends orchestration config file with sections for hotpot and gelato configs. This PR depends on https://github.com/opensds/orchestration/pull/79
> Update orchestration config with hotpot and gelato details

- ansible/group_vars/common.yml
- charts/csiplugin/Chart.yaml
- charts/csiplugin/values.yaml
- charts/opensds/Chart.yaml
- charts/opensds/values.yaml
- charts/servicebroker/Chart.yaml
- charts/servicebroker/values.yaml
> modify the tag version

- ansible/group_vars/orchestration.yml
- ansible/roles/cleaner/scenarios/release.yml
- ansible/roles/orchestration-installer/scenarios/source-code.yml
This PR adds support for release install for orchestration
> Add release installation support for orchestration

- ansible/group_vars/telemetry.yml
- ansible/roles/telemetry-installer/scenarios/install_telemetry_tools.yml
- ansible/script/mod_prometheus_config_for_lvm_exporter.sh
- ansible/script/set_lvm_exporter_service.sh
This PR will change port for lvm_export from 8080 to 9094.
This PR will address issue #223
> Change port for telemetry lvm_exporter

- ansible/group_vars/telemetry.yml
> Change lvm_exporter port

- ansible/group_vars/common.yml
- charts/OpenSDS Installation using Helm.md
- charts/csiplugin/Chart.yaml
- charts/csiplugin/values.yaml
- charts/opensds/Chart.yaml
- charts/opensds/values.yaml
- charts/servicebroker/Chart.yaml
- charts/servicebroker/values.yaml
> Just for Capri release

- ansible/group_vars/telemetry.yml
- ansible/roles/telemetry-installer/scenarios/install_telemetry_tools.yml
- ansible/roles/telemetry-uninstaller/scenarios/clean_telemetry_tools.yml
This PR cherry-picks Changing Grafana repository location commit from master to stable/capri.
> Cherry-Pick grafana repositroy location fix to stable/capri

- salt/README.md
> docs(readme): fix readme for salt

- salt/README.md
- salt/install.sh
- salt/srv/pillar/site.j2
> chore(salt): bump versions for capri release

- salt/ea/package_ea.sh
- salt/install.sh
- salt/salt-bootstrap.sh
- salt/srv/pillar/opensds.sls
- salt/srv/pillar/salt.sls
- salt/srv/salt/install/salt.sls
- salt/srv/salt/remove/salt.sls
This PR bumps versions to python3 and salt 2019.2.  Verified on Ubuntu/CentOS/Suse
> feat(salt): use python3 and salt 2019.2

- ansible/group_vars/common.yml
- charts/OpenSDS Installation using Helm.md
- charts/csiplugin/Chart.yaml
- charts/csiplugin/values.yaml
- charts/opensds/Chart.yaml
- charts/opensds/values.yaml
- charts/servicebroker/Chart.yaml
- charts/servicebroker/values.yaml
modify the version tag to v0.6.1
> modify the version tag to v0.6.1

- salt/README.md
- salt/srv/pillar/site.j2
> docs(salt): fix osdsctl command in readme

- ansible/docs/OpenSDS Multi-nodes installation using Ansible.md
issue #244 
This PR update the OpenSDS multi-nodes installation steps, to capture multi-nodes specific steps in the document. This is to keep common steps in 'OpenSDS Cluster Installation through Ansible' wiki page for easier maintenance.
> Update OpenSDS multi-nodes installation document

- salt/README.md
Remove unnecessary `sudo -s` step.
> docs(salt): minor readme update

- salt/salter.sh
This PR merges changes added to upstream `salter.sh` fork in repo:
https://github.com/saltstack-formulas/salter/blob/master/salter.sh
This PR includes a CentOS fix documented in https://github.com/saltstack-formulas/salter/pull/54
> Merge changes from upstream repo

- ansible/roles/common/scenarios/repository.yml
- ansible/roles/hotpot-installer/tasks/main.yml
This pr will enable api validation of hotpot in opensds-installer, see: opensds/opensds#990
> Add open api spec configuration of hotpot

- ansible/roles/gelato-installer/scenarios/repository.yml
- ansible/script/sdsrc
This is a workaround for the multicloud installation failure.
> Workaround for multi-cloud installation failure

- ansible/roles/gelato-installer/tasks/main.yml
> Add libradosstriper-dev package for ubuntu multi-cloud installation

- ansible/roles/gelato-installer/scenarios/release.yml
This PR is to support Multi-Cloud installation for release tag
> Fix multicloud build for release tags

- ansible/roles/sushi-installer/scenarios/repository.yml
**What this PR does / why we need it:**
This PR is for the installer files update related to host api changes.
This PR disables flex volume installation which is obselete
**Which issue this PR fixes (optional, in fixes #(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged): fixes #**
Part of fix for NBP changes for host api changes
**Special notes for your reviewer:**
This is the installer update corresponding to the implementation PR
https://github.com/opensds/nbp/pull/293
Test report:
[test-reports-installer.zip](https://github.com/opensds/opensds-installer/files/3888339/test-reports-installer.zip)
**Release note:**
> Installer changes for NBP part due to host api changes

- ansible/group_vars/common.yml
- ansible/roles/hotpot-installer/tasks/main.yml
- ansible/roles/osdsdock/scenarios/ceph.yml
- ansible/roles/osdsdock/scenarios/lvm.yml
- ansible/roles/osdsdock/scenarios/nfs.yml
- ansible/roles/osdsdock/tasks/main.yml
This PR address issue #278 and add following features
Clean up config file create and update using ansible module 'ini_file'
> Use ini_file module of Ansible for config file create and update

- ansible/group_vars/common.yml
- charts/OpenSDS Installation using Helm.md
- charts/csiplugin-block/values.yaml
- charts/csiplugin-file/values.yaml
- charts/opensds/values.yaml
- charts/servicebroker/values.yaml
Updates the release to tag v0.7.0
Addresses issue #298
> Update to release version v0.7.0

- ansible/group_vars/common.yml
- ansible/group_vars/gelato.yml
- charts/OpenSDS Installation using Helm.md
- charts/csiplugin-block/values.yaml
- charts/csiplugin-file/values.yaml
- charts/opensds/values.yaml
- charts/servicebroker/values.yaml
Update release tag for Daito RC4 release
> Update release tag: v0.9.0

- ansible/group_vars/common.yml
- charts/OpenSDS Installation using Helm.md
- charts/csiplugin-block/values.yaml
- charts/csiplugin-file/values.yaml
- charts/opensds/values.yaml
- charts/servicebroker/values.yaml
Release tag is updated to v0.10.0 for Daito release
> Update tag for Daito release v0.10.0

- ansible/group_vars/hotpot.yml
Installer version update with v0.10.1. (For this tag only hotpot tag is changed)
> Update installer for tag v0.10.1

- ansible/roles/cleaner/scenarios/backend.yml
- ansible/roles/cleaner/tasks/main.yml
> Fixes cleanup of lvm loop devices

- ansible/clean.yml
- ansible/group_vars/sim.yml
- ansible/roles/cleaner/scenarios/sim.yml
- ansible/roles/cleaner/tasks/main.yml
- ansible/roles/sim-installer/scenarios/rabbitmq.yml
- ansible/roles/sim-installer/scenarios/redis.yml
- ansible/roles/sim-installer/scenarios/source-code.yml
- ansible/roles/sim-installer/scenarios/start-sim.yml
- ansible/roles/sim-installer/tasks/main.yml
- ansible/script/create_db.py
- ansible/script/virtualenv3_exec.j2
- ansible/site.yml
>
This PR implements installation of SIM project
Fixes #
> /kind TESTED
Steps to use SIM installation:
1. Change file ansible/group_vars/sim.yml, "enable_sim: true"
2. Run following command to install only SIM: "installer/ansible# ansible-playbook site.yml -i local.hosts -vv --tags sim"
3. Run following command to Cleanup SIM: "installer/ansible# …
> Add support for SIM installation

- ansible/script/create_db.py
1. rename dolphin to delfin
2. craete required db file folder
3. allow rabbit-mq install
Fixes #362
> /kind TESTED
PLAY RECAP **************************************************************************************************************************************************
localhost                  : ok=22   changed=8    unreachable=0    failed=0
NA
> SIM Installer : Create DB enhancement

- ansible/roles/dashboard-installer/scenarios/container.yml
This PR adds the environment variables needed for the change in port of S3 APIs in multicloud. 
Fixes #367 
/kind NOT-TESTED
> Updated Environment variable configuration for Dashboard installation with S3 API endpoint

- ansible/group_vars/dashboard.yml
- ansible/group_vars/hotpot.yml
- ansible/roles/gelato-installer/scenarios/repository.yml
- ansible/roles/gelato-installer/tasks/main.yml
- charts/csiplugin-block/values.yaml
- charts/csiplugin-file/values.yaml
- charts/opensds/values.yaml
- charts/servicebroker/values.yaml
- salt/pillar_roots/site.j2
>
> /kind design
Rename api/controller/dock images to sodafoundtion/*
Fixes #
> /kind TESTED
> Rename api/controller/dock images to sodafoundation/*

- ansible/group_vars/common.yml
- ansible/group_vars/dashboard.yml
- charts/OpenSDS Installation using Helm.md
- charts/csiplugin-block/values.yaml
- charts/csiplugin-file/values.yaml
- charts/opensds/values.yaml
- charts/servicebroker/values.yaml
>
> /kind design
Update installer tags to v1.0.0
Fixes #
> /kind TESTED
> Update installer tags to v1.0.0

- ansible/group_vars/delfin.yml
- ansible/roles/delfin-installer/scenarios/redis.yml
- ansible/roles/delfin-installer/scenarios/source-code.yml
>
> /kind design
Change default port of redis to support delfin installation with multi-cloud
Fixes #
> /kind TESTED
> Change default port of redis to support delfin installation with multi-cloud

- ansible/group_vars/orchestration.yml
- ansible/roles/common/tasks/main.yml
- ansible/site.yml
>
kind new feature
> /kind design
This code change will add support for CentOS. 
Code changes made to support CentOS and changes made for supporting RHEL too. Testing being done only for CentOS.
This is first of series of changes to be done.
TODO: Add proper installation of iscsi package and gelato fixes
Fixes #377 
kind TESTED
> …
> Support installation on CentOS

- ansible/group_vars/common.yml
- ansible/group_vars/delfin.yml
- ansible/group_vars/hotpot.yml
- charts/OpenSDS Installation using Helm.md
- charts/csiplugin-block/values.yaml
- charts/csiplugin-file/values.yaml
- charts/opensds/values.yaml
- charts/servicebroker/values.yaml
Update tag for release version v1.0.1
>
> /kind design
Fixes #
> /kind TESTED
> WIP:Update tag for release version v1.0.1

- ansible/group_vars/dashboard.yml
Fix dashboard image release version
>
> /kind design
Fixes #
> /kind TESTED
> Fix dashboard image release version

- ansible/roles/cleaner/scenarios/delfin.yml
- ansible/roles/delfin-installer/scenarios/redis.yml
- ansible/site.yml
>
/kind bug fix
After redis config change restart redis service.
Fixes #391
> /kind TESTED
> After redis config change restart service

- ansible/roles/cleaner/scenarios/delfin.yml
- ansible/roles/delfin-installer/scenarios/source-code.yml
- ansible/roles/delfin-installer/scenarios/start-delfin.yml
>
> /kind design
To support performance collection, need to start and stop/clean process of exporter process.
Fixes #
> /kind TESTED
After installtion. All process are running
> Adding Performance installtion to ansible

- ansible/group_vars/delfin.yml
- ansible/roles/delfin-installer/scenarios/source-code.yml
- ansible/roles/delfin-installer/scenarios/start-delfin.yml
Support Delfin performance exporters and alert exporter configs from Ansible Installer
Fixes #
> /kind TESTED
> Support Delfin performance exporters and alert exporter configs

- ansible/group_vars/common.yml
- ansible/group_vars/delfin.yml
- ansible/group_vars/gelato.yml
- ansible/group_vars/hotpot.yml
- ansible/group_vars/orchestration.yml
- ansible/group_vars/sushi.yml
>
> /kind design
Adding release tags for the Hawaii RC1 projects
Fixes #
> /kind TESTED
Hawaii RC1 has only Delfin, Dashboard and Gelato projects update.
> Adding the Hawaii RC1 release tags.

- ansible/group_vars/delfin.yml
- ansible/roles/delfin-installer/scenarios/rabbitmq.yml
Fix delfin OS version for supporting both 18.04 & 16.04
>
> /kind design
Fixes #
> /kind TESTED
> Fix delfin OS version for 18.04 & 16.04

- ansible/group_vars/common.yml
- ansible/group_vars/dashboard.yml
- ansible/group_vars/delfin.yml
>
> /kind design
Adding the release tag for Hawaii RC2
Fixes #
> /kind TESTED
> Added Hawaii RC2 release tag

- ansible/group_vars/common.yml
- charts/OpenSDS Installation using Helm.md
- charts/csiplugin-block/values.yaml
- charts/csiplugin-file/values.yaml
- charts/opensds/values.yaml
>
> /kind design
Add I-RC1 release tags for the projects
Fixes #
> /kind TESTED
> Installer update for I-RC1 release

- ansible/clean.yml
- ansible/group_vars/common.yml
- ansible/group_vars/gelato-ha.yml
- ansible/local.hosts
- ansible/roles/gelato-ha-installer/tasks/main.yml
- ansible/roles/gelato-ha-uninstaller/scenarios/clean_gelato_ha.yml
- ansible/roles/ha-ip-update/tasks/main.yml
Makes  K8s user configurable. 
>
User should be able to configure the user that can access K8s for deploying multi-cloud HA 
Fixes #
> /kind TESTED
> Make K8s user configurable

- ansible/group_vars/gelato-ha.yml
- ansible/roles/gelato-ha-installer/scenarios/release.yml
- ansible/roles/gelato-ha-installer/tasks/main.yml
- ansible/site.yml
PR is to use gelato_release_version to deploy pods in multi-cloud HA installation. 
>
kind bug fix
> /kind design
PR is to use gelato_release_version to deploy pods in multi-cloud HA installation. 
Fixes #441 
> /kind TESTED
> use gelato_release_version to deploy pods

- ansible/group_vars/common.yml
- charts/opensds/values.yaml
>
> /kind design
Add I-RC3 release tags for the projects
Fixes #
> /kind TESTED
> Release tag update for Isabela-RC3

- ansible/group_vars/common.yml
- charts/OpenSDS Installation using Helm.md
- charts/csiplugin-block/values.yaml
- charts/csiplugin-file/values.yaml
- charts/opensds/values.yaml
>
> /kind design
Add Isabela release tags for the projects
Fixes #
> /kind TESTED
> Release tag update for Isabela

- ansible/srm-toolchain/prometheus/alerts.rules
This PR fixes the metric names in the sample alert rules setup in Prometheus to generate alerts using the metrics generated by Alertmanager.
Fixes #
/kind TESTED
> Updated the metric names in the sample alerts generated by Prometheus using the delfin metrics.

- ansible/group_vars/delfin.yml
- ansible/roles/cleaner/scenarios/delfin.yml
- ansible/roles/delfin-installer/scenarios/container.yml
- ansible/roles/delfin-installer/scenarios/source-code.yml
- ansible/roles/delfin-installer/tasks/main.yml
Add installer support for delfin containerized deployment
>
> /kind design
Fixes #460 
> /kind TESTED
> Add installer support for delfin containerized deployment

- ansible/group_vars/common.yml
- charts/OpenSDS Installation using Helm.md
- charts/csiplugin-block/values.yaml
- charts/csiplugin-file/values.yaml
- charts/opensds/values.yaml
- charts/servicebroker/values.yaml
Update SODA project tags for Jerba RC1 release
Fixes #
> /kind TESTED
> Update SODA project tags for Jerba RC1 release

- ansible/group_vars/common.yml
- charts/opensds/values.yaml
Update SODA project tags for Jerba RC2 release
>
> /kind design
Fixes #
> /kind TESTED
> Update SODA project tags for Jerba RC2 release

- ansible/roles/gelato-installer/tasks/main.yml
- ansible/script/keystone.sh
Add HOST_IP of Keystone for creating AKSK
>
kind bug fix
Host_IP of the Keystone host was not getting replaced in docker-compose.yml
without this fix, AKSK will not get generated using AKSKS API.
Fixes #469
kind TESTED
IP is replaced in docker-compose after fix. 
> Add HOST_IP of Keystone for creating AKSK

- ansible/group_vars/common.yml
- charts/opensds/values.yaml
>
> /kind design
Update SODA project tags for Jerba RC3 release
Fixes #
> /kind TESTED
> Update SODA project tags for Jerba RC3 release

- ansible/group_vars/common.yml
- charts/OpenSDS Installation using Helm.md
- charts/csiplugin-block/values.yaml
- charts/csiplugin-file/values.yaml
- charts/opensds/values.yaml
- charts/servicebroker/values.yaml
Update SODA project tags for Jerba 1.4.0 release
Fixes #
> /kind TESTED
> Update SODA project tags for Jerba 1.4.0 release

- ansible/site.yml
>
> /kind design
/kind bug fix
It renames OpenSDS Hotpot to SODA Hotpot(api, controller, dock) as Hotpot project has been split to api, controller and dock.
Fixes #
> /kind TESTED
> Rename OpenSDS Hotpot to SODA Hotpot in ansible site.yml

- .github/workflows/ci_pull_request.yml
- .github/workflows/ci_push.yml
>
> /kind design
Remove Ubuntu 16.04 from CI
Fixes #
> /kind TESTED
> Remove Ubuntu 16.04 from CI

- ansible/group_vars/common.yml
- charts/opensds/values.yaml
Update SODA project tas for Kalpeni RC1 release
Fixes #
> /kind TESTED
> Update SODA project tags for Kalpeni RC1 release

- ansible/group_vars/delfin.yml
- ansible/roles/delfin-installer/scenarios/source-code.yml
>
> /kind design
Add option to enable delfin dynamic process optimization
Fixes #
> /kind TESTED
> Add option to enable delfin dynamic process optimization

- ansible/group_vars/common.yml
- charts/opensds/values.yaml
>
> /kind design
Update SODA project tags for Kalpeni release
Fixes #
> /kind TESTED
Release build
> Update SODA proect tags for Kalpeni release

- ansible/group_vars/common.yml
- charts/opensds/values.yaml
Update SODA Projects tags for L RC1 release
>
> /kind design
Fixes #
> /kind TESTED
> Update SODA Projects tags for L RC1 release

- ansible/group_vars/common.yml
Update SODA Projects tags for L RC2 release
Fixes #
> /kind TESTED
> Update SODA Projects tags for L RC2 release

- ansible/group_vars/common.yml
- charts/opensds/values.yaml
Update SODA Projects tags for L v1.6.0 release
Fixes #
> /kind TESTED
> Update SODA Projects tags for L v1.6.0 release

- ansible/group_vars/common.yml
- charts/opensds/values.yaml
Update SODA projects tags for Madagascar RC1 release
Update SODA projects tags for Madagascar RC1 release
Fixes #
> /kind TESTED
> Update SODA projects tags for Madagascar RC1 release

- README.md
- ansible/install_dependencies.sh
Fix for despondency lib installation
Which issue(s) this PR fixes:
Fixes #
Test Report Added?:
> /kind TESTED
Test Report:
Special notes for your reviewer:
> Installer Script Fix

- ansible/group_vars/delfin.yml
- ansible/roles/delfin-installer/scenarios/delfin_install.yml
- ansible/roles/gelato-installer/scenarios/gelato_install.yml
Check ansible-playbook execution status for delfin individual installer
>
> /kind design
Fixes #
> /kind TESTED
> Check ansible-playbook execution status for delfin & multicloud installer

- ansible/install_dependencies.sh
bug fix
Fix for docker installation
Which issue(s) this PR fixes:
Fixes 
Test Report Added?:
> /kind TESTED
Test Report:
> Docker installation fix

- ansible/group_vars/dashboard.yml
- ansible/group_vars/delfin.yml
- ansible/group_vars/gelato.yml
- charts/opensds/values.yaml
Update SODA Projects tags for v1.8.0 release
>
> /kind design
Fixes #
> /kind TESTED
> Release Tag changes

- ansible/group_vars/delfin.yml
Update Delfin Release tags for v1.8.0 release
Uncomment only one  /kind <> line, hit enter to put that in a new line, and remove leading whitespace from that line:
/kind bug fix
/kind cleanup
/kind revert change
/kind design
/kind documentation
Which issue(s) this PR fixes:
Fixes #
Test Report Added?:
Uncomment only one  /kind <> line, hit enter to put that in a new line, and remove leading whitespace from that line:
/kind TESTED
/kind NOT-TESTED
Test Report:
Special notes for your reviewer:
> Updated Delfin Release tag

- ansible/group_vars/dashboard.yml
- ansible/group_vars/delfin.yml
- ansible/group_vars/gelato.yml
- charts/opensds/values.yaml
Update SODA Projects tags for v1.8.0 release
/kind design
/kind documentation
Release version update
Which issue(s) this PR fixes:
Fixes #
Test Report Added?:
Uncomment only one  /kind <> line, hit enter to put that in a new line, and remove leading whitespace from that line:
/kind TESTED
/kind NOT-TESTED
Test Report:
Special notes for your reviewer:
> Release Tag Update

- README.md
Increases readability of documentation and provides more examples to new user
Fixes #
> /kind TESTED
- Strato installation example added in readme
- Delfin installation example updated
> Document update for readme to add example for strato(multi-cloud) also

- ansible/clean.yml
- ansible/group_vars/delfin-ui.yml
- ansible/roles/cleaner/scenarios/delfin-ui.yml
- ansible/roles/cleaner/tasks/main.yml
- ansible/roles/delfin-ui-installer/scenarios/container.yml
- ansible/roles/delfin-ui-installer/tasks/main.yml
- ansible/site.yml
This PR adds the installation and clean up configuration for the Delfin UI.
Fixes #567 
/kind TESTED
> Added Delfin UI installer and clean up

- ansible/group_vars/delfin-ui.yml
- ansible/group_vars/delfin.yml
- ansible/group_vars/gelato.yml
- ansible/group_vars/strato-ui.yml
kind bug fix
This PR adds Okinawa Release tag update for installer
Fixes #
> /kind TESTED
> Okinawa Release tag update

- ansible/group_vars/delfin.yml
- ansible/group_vars/gelato.yml
>
> /kind design
Fixes #
> /kind TESTED
> P Release tag update
